# SERVER
server.port=9696

# POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5000/library
spring.datasource.username=postgres
spring.datasource.password=Azert@12345
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# MONGODB ATLAS
spring.data.mongodb.uri=mongodb+srv://admin:Admin123@dbms1.5xcwisz.mongodb.net/library?retryWrites=true&w=majority&appName=DBMS1

# JWT
library.jwtSecret=monochromeBlackAndWhiteElegantThemeDigitalLibrarySystemJWTSecretKey2026
library.jwtExpirationMs=86400000