# SERVER
server.port=9191

# POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5000/library
spring.datasource.username=postgres
spring.datasource.password=Azert@12345
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# MONGODB
spring.data.mongodb.uri=mongodb://localhost:27017/library

# JWT
library.jwtSecret=monochromeBlackAndWhiteElegantThemeDigitalLibrarySystemJWTSecretKey2026
library.jwtExpirationMs=86400000